remote_theme: pages-themes/minimal@v0.2.0
title: Explainable Cross-Lingual Text Retrieval on Automotive domain
logo: https://raw.githubusercontent.com/vijusudhi/cltr_web_app/master/multilingual-icon-9.jpg
mail_url: mailto:vjusudhi@gmail.com
